# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21
yarn_mappings=1.21+build.9
loader_version=0.16.9

#Fabric api
fabric_version=0.102.0+1.21

# Mod Properties
mod_version=3.1.1
maven_group=witcher.medallions
archives_base_name=witcher-medallions

# Dependencies
trinkets_version=3.10.0
geckolib_version=4.5.8
owo_version=0.12.15+1.21

# Witcher RPG
spell_engine_version=1.2.2+1.21.1
azure_lib_version=2.3.2
spell_power_version=1.0.4+1.21.1

player_anim_version=2.0.0-alpha1+1.21
cloth_config_version=15.0.130
tiny_config_version=2.3.2

