# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=3.1.1
group=witcher.medallions
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Witcher Medallions
mod_author=Tenebris Mors
mod_id=witcher_medallions
license=MIT
credits=
description=A simple mod that adds Witcher Medallions!
minecraft_version_range=[1.21, 1.22)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# See version here https://fabricmc.net/develop/
# Fabric
fabric_version=0.115.4+1.21.1
fabric_loader_version=0.16.13

# Forge
forge_version=52.0.28
forge_loader_version_range=[52,)

# See version here https://projects.neoforged.net/neoforged/neoforge
# NeoForge
neoforge_version=21.1.146
neoforge_loader_version_range=[4,)

# Common Dependencies
# See version here https://www.curseforge.com/minecraft/mc-mods/geckolib/files/all
geckolib_version=4.7.5.1
# See version here https://modrinth.com/mod/owo-lib/versions
owo_version=0.12.15.1+1.21
owo_version_neo=0.12.15.1-beta.2+1.21


#NeoForge Dependencies
# See version here https://www.curseforge.com/minecraft/mc-mods/curios/files/all
curios_version=9.2.0+1.21.1

#Fabric Dependencies
# See version here https://www.curseforge.com/minecraft/mc-mods/trinkets/files/all
trinkets_version=3.10.0

# Witcher RPG
# See version here https://www.curseforge.com/minecraft/mc-mods/spell-engine/files/all
spell_engine_version=1.6.6+1.21.1
# See version here https://modrinth.com/mod/azurelib/versions
azure_lib_version=3.0.2
# See version here https://www.curseforge.com/minecraft/mc-mods/spell-power/files/all
spell_power_version=1.2.3+1.21.1

# See version here https://www.curseforge.com/minecraft/mc-mods/playeranimator/files/all
player_anim_version=2.0.1+1.21.1
# See version here https://modrinth.com/mod/cloth-config/versions
cloth_config_version=15.0.140
tiny_config_version=2.3.2
